export const VIEW_PREVIEW='VIEW_PREVIEW';

export const UPDATE_FORM_TITLE='UPDATE_FORM_TITLE';

export const ADD_NEW_FORM_ELEMENT='ADD_NEW_FORM_ELEMENT';
export const DELETE_FORM_ELEMENT='DELETE_FORM_ELEMENT';

export const ADD_NEW_TICK_BOX='ADD_NEW_TICK_BOX';
export const DELETE_TICK_BOX='DELETE_TICK_BOX';

export const UPDATE_TITLE_TEXT='UPDATE_TITLE_TEXT';
export const UPDATE_TICK_BOX_TEXT='UPDATE_TICK_BOX_TEXT';

export const UPDATE_TICK_BOX_VALUE='UPDATE_TICK_BOX_VALUE';
export const UPDATE_TEXT_AREA_VALUE='UPDATE_TEXT_AREA_VALUE';